sudo: required
os: osx
language: generic

env:
  global:
    - ANSIBLE_ROLES_PATH=$TRAVIS_BUILD_DIR/..
  matrix:
    - ANSIBLE_VERSION=ansible19
    - ANSIBLE_VERSION=ansible20

install:
  - brew update
  - brew tap homebrew/versions
  - brew install $ANSIBLE_VERSION
  - gem install inspec --no-rdoc --no-ri

script:
  - ansible-playbook -i localhost, -c local test/integration/default/default.yml
  - >
    ansible-playbook -i localhost, -c local test/integration/default/default.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - inspec exec test/integration/default/role_spec.rb
