---
sudo: required
os: osx
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  
env:
  global:
    - ANSIBLE_ROLES_PATH=$TRAVIS_BUILD_DIR/..
  matrix:
    - ANSIBLE_VERSION=ansible==1.9
    - ANSIBLE_VERSION=ansible==2.0

install:
  - pip install $ANSIBLE_VERSION
  - gem install inspec --no-rdoc --no-ri

script:
  - ansible-playbook -i localhost, -c local test/integration/default/default.yml
  - >
    ansible-playbook -i localhost, -c local test/integration/default/default.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - inspec exec test/integration/default/role_spec.rb
