---
- name: check if homebrew is present
  command: /usr/local/bin/brew --version
  register: result
  changed_when: False
  ignore_errors: true

- name: install homebrew if needed
  shell: echo | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: result|failed

- name: Ensure configured taps are tapped.
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: Install brew packages
  homebrew:
    name: "{{ item }}"
    state: latest
    update_homebrew: yes
  with_items: "{{ homebrew_packages }}"

- name: Install cask apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_casks }}"
  when: "'caskroom/cask' in homebrew_taps"
