---
- name: check if homebrew is present
  command: /usr/local/bin/brew --version
  register: result
  ignore_errors: true

- name: install homebrew if needed
  shell: echo|ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: result|failed

- name: run brew prune
  shell: /usr/local/bin/brew prune

- name: run brew update
  shell: /usr/local/bin/brew update

- name: run brew doctor
  shell: /usr/local/bin/brew doctor
  when: not ansible_distribution_version | match('10.11')
  ignore_errors: true
